apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p5d565n1o-go
  janus-idp.io/tekton: p5d565n1o-go
  backstage.io/kubernetes-id: p5d565n1o-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p5d565n1o-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
